### ISSUE TITLE
Test description unclear/different than README instructions

### ISSUE THREAD

**Issue by thuyanduong-flatiron** [learn-co-curriculum/fewpjs-js-fundamentals-arrays-lab#3]
README says to write for arrays named append, prepend, removeLast, and removeFirst

But test description says to write functions removeLastDriver(), removeFirstDriver(), etc.

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
